Image.create(:image => open("#{Rails.root}/db/fixtures/topps03.jpeg"), :item_id =>'5')
Image.create(:image => open("#{Rails.root}/db/fixtures/topps04.jpeg"), :item_id =>'6')
Image.create(:image => open("#{Rails.root}/db/fixtures/ladys01.jpeg"), :item_id =>'7')
Image.create(:image => open("#{Rails.root}/db/fixtures/ladys02.jpeg"), :item_id =>'8')
Image.create(:image => open("#{Rails.root}/db/fixtures/ladys03.jpeg"), :item_id =>'3')
Image.create(:image => open("#{Rails.root}/db/fixtures/topps02.jpg"), :item_id =>'3')
Image.create(:image => open("#{Rails.root}/db/fixtures/topps01.jpg"), :item_id =>'3')
Image.create(:image => open("#{Rails.root}/db/fixtures/topps02.jpg"), :item_id =>'4')